base:
  alpine-3: 
    Dockerfile: Dockerfile.alpine
    config.yaml: config.yaml
  debian-11: 
    Dockerfile: Dockerfile.debian
    config.yaml: config.yaml

platform:
  - linux/amd64
  - linux/arm64

version:
  - 0.25.4
