ARG BASE=_BASE_

FROM ${BASE}

ARG VERSION BUILDPLATFORM BUILDOS BUILDARCH TARGETPLATFORM TARGETOS TARGETARCH 

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y wget curl && \
    wget https://github.com/shidaxi/chain-exporter/releases/download/v${VERSION}/chain-exporter-${TARGETOS}-${TARGETARCH}.tar.gz \
    -O - | tar xzf - -C /usr/local/bin/ && \
    apt clean all
