ARG BASE=_BASE_

FROM ${BASE}

ARG VERSION BUILDPLATFORM BUILDOS BUILDARCH TARGETPLATFORM TARGETOS TARGETARCH 

RUN apk add --no-cache ca-certificates && \
    wget https://github.com/shidaxi/chain-exporter/releases/download/v${VERSION}/chain-exporter-${TARGETOS}-${TARGETARCH}.tar.gz \
    -O - | tar xzf - -C /usr/local/bin/