base:
  alpine:3: &alpine3
    Dockerfile: Dockerfile.alpine
  alpine:3.18: *alpine3
  alpine:3.17: *alpine3
  debian:11: &debian11
    Dockerfile: Dockerfile.debian
  debian:bullseye: *debian11

arch:
  - linux/386
  - linux/amd64
  - linux/arm/v7
  - linux/arm64/v8
  - linux/ppc64le
  - linux/s390x

version:
  - v0.1
  - v0.2
