ARG BASE
ARG VERSION
FROM ${BASE/-/:}
COPY --chmod=755 <<EOF /app/run.sh
#!/bin/sh
while true; do
  echo -ne "The time is now $(date +%T), apt install, version ${VERSION}\\r"
  sleep 1
done
EOF

ENTRYPOINT /app/run.sh
