base:
  python-3.10.13-alpine:
    requirements.txt: requirements.txt
    Dockerfile: Dockerfile.alpine
  python-3.10.13-slim-bullseye:
    requirements.txt: requirements.txt
    Dockerfile: Dockerfile.debian

platform:
  - linux/amd64
  - linux/arm64

version:
  - v2.17.0
