base:
  node-16-alpine: 
    Dockerfile: Dockerfile.alpine
  node-16-bulleye: 
    Dockerfile: Dockerfile.debian

platform:
  - linux/amd64
  - linux/arm64/v8
  - linux/ppc64le
  - linux/s390x

version:
  - 1.19
  