base:
  op-base-0.2.0:
    Dockerfile: Dockerfile.debian
    apps: apps
    app.py: app.py
    command.py: command.py
    requirements.txt: requirements.txt

platform:
  - linux/amd64
  - linux/arm64

version:
  - 0.2.0
  
