ARG VERSION

FROM shidaxi/op-base:0.2.0-node-16-bullseye

ARG BUILDPLATFORM BUILDOS BUILDARCH TARGETPLATFORM TARGETOS TARGETARCH

ADD requirements.txt .

RUN apt install python3-pip -y && \
    pip install -r requirements.txt && \
    mkdir -p /app

WORKDIR /app

ADD *.py .
ADD apps ./apps

ENV FLASK_ENV=development
ENV FLASK_APP=app.py

ENTRYPOINT ["flask", "run", "-h", "0.0.0.0"]