ARG BASE=_BASE_
ARG VERSION

FROM ${BASE}

ARG BUILDPLATFORM BUILDOS BUILDARCH TARGETPLATFORM TARGETOS TARGETARCH 

RUN apt update -y && \
    apt install -y psmisc procps net-tools iputils-ping iproute2 dnsutils tcpdump nmap vim bc wget curl git build-essential libclang-dev python3 jq unzip screen netcat-openbsd telnet
