name: Test workflow
on:
  workflow_dispatch:
    inputs:
      appName:
        description: App name to Build
        type: choice
        required: true
        default: a0examplegolang
        options:
        - a0examplegolang
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set APP Info
        id: appinfo
        run: |
          echo Hi
