base:
  alpine-3: 
    Dockerfile: Dockerfile.alpine
    run.sh: run.sh
  debian-11: 
    Dockerfile: Dockerfile.debian
    run.sh: run.sh
platform:
  - linux/386
  - linux/amd64
  - linux/arm/v7
  - linux/arm64/v8
  - linux/ppc64le
  - linux/s390x

version:
  - v0.1
  - v0.2