base:
  alpine-3:
    Dockerfile: Dockerfile.alpine
  alpine-3.18:
    Dockerfile: Dockerfile.alpine
  alpine-3.17:
    Dockerfile: Dockerfile.alpine
  debian-11:
    Dockerfile: Dockerfile.debian
  debian-bullseye:
    Dockerfile: Dockerfile.debian

arch:
  - linux/386
  - linux/amd64
  - linux/arm/v7
  - linux/arm64/v8
  - linux/ppc64le
  - linux/s390x

version:
  - v0.1
  - v0.2
